language: python

# Force master and develop only
branches:
  only:
    - master
    - develop

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-9.0
          packages:
            - clang-9.0
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"
    - os: osx
      osx_image: xcode8

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - . ./init.sh
  - scons -j 2 debug=False
  - scons -j 2 debug=False test
