sudo: true
language: generic

# Force master and develop only
branches:
  only:
    - master
    - develop

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - python3-pip
            - python3-setuptools
      env:
        - CC=gcc-9
        - CXX=g++-9
        - TOXENV=py38
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-10
            - python3-pip
            - python3-setuptools
            - libstdc++6
            - libstdc++6-9-dev
      env:
        - CC=clang-10
        - CXX=clang++-10
        - TOXENV=py38
    - os: osx
      osx_image: xcode12.2
      env:
        - TOXENV=py38
      before_install:
        - brew install python@3.8


script:
  - . ./.travis/script.sh
