version: Build {build} @ {branch}

environment:
  matrix:
    - M_PYTHON: "C:\\Python38-x64"

  
branches:
  only:
    - master
    - develop

skip_tags: true

skip_commits:
  message: /.*\[skip-ci\].*/

image: Visual Studio 2019

install:
  - git submodule update --init --recursive
  - ps: if (-not(Test-Path($env:M_PYTHON))) { & appveyor\install.ps1 }
  - "SET PATH=%M_PYTHON%;%M_PYTHON%\\Scripts;%PATH%"
  - python -m pip install setuptools
  - python -m pip install scons conan
  - conan profile create --detect default
  - conan profile update settings.compiler.runtime=MT default
  - scons -j 2
  - scons -j 2 test
