version: Build {build} @ {branch}

branches:
  only:
    - master
    - develop

skip_tags: true

skip_commits:
  message: /.*\[skip-ci\].*/

image: Visual Studio 2019

services:
  - python3
install:
  - python -m pip install setuptools
  - python -m pip install scons conan
  - scons -j 2
  - scons -j 2 test
