version: Build {build} @ {branch}

environment:
  matrix:
    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.x"
      PYTHON_ARCH: "64"
  
branches:
  only:
    - master
    - develop

skip_tags: true

skip_commits:
  message: /.*\[skip-ci\].*/

image: Visual Studio 2019

install:
  - ps: if (-not(Test-Path($env:PYTHON))) { & appveyor\install.ps1 }
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python -m pip install setuptools
  - python -m pip install scons conan
  - scons -j 2
  - scons -j 2 test
