import os
import pathlib
from sys import platform
Import("env")
Import("lpath")
Import("database")

env.withLibraries("taskrangersources", append = False)
env.appendLibPath("#" + lpath)
env.withConan(conanfile = os.path.join(Dir("#").abspath, "tests/conanfile.py"), remotes = [{"remote_name": "catch2", "url": "https://api.bintray.com/conan/catchorg/Catch2"}])

env.appendSourcePath("#tests/testSources")

tests = env.Program("tests", env.Glob("testSources/*.cpp"))

testAlias = env.environment.Alias("test", [ tests ], tests[0].abspath)
if "test" in BUILD_TARGETS:
    AlwaysBuild(testAlias)

# Hack to make sure the database is built
if (database is not None):
    Depends(tests, database)
