Import("env")

sources = env.Glob("taskranger/input/*.cpp")
sources += env.Glob("taskranger/input/operators/*.cpp")
sources += env.Glob("taskranger/commands/*.cpp")
sources += env.Glob("taskranger/util/*.cpp")
sources += env.Glob("taskranger/data/*.cpp")
sources += env.Glob("taskranger/data/attributes/*.cpp")
sources += env.Glob("taskranger/config/*.cpp")

env.appendSourcePath("#src/")
env.appendSourcePath("#tabulate/include")

if "test" in BUILD_TARGETS:
    lib = env.Library("taskranger", sources)
    Default(lib)
else:
    sources += env.Glob("taskranger/*.cpp")
    # The executable is named after the program instead of a shorthand function in order to avoid collisions with other todo programs.
    # Shell aliases can be manually added if necessary.
    # python/SourceList.py contains the list of sources.
    # It's kept externally because it's also used in tests/SConscript
    exe = env.Program("taskranger", sources)
    Default(exe)
