Import("env")
Import("database")

sources = env.Glob("taskranger/input/*.cpp")
sources += env.Glob("taskranger/input/operators/*.cpp")
sources += env.Glob("taskranger/commands/*.cpp")
sources += env.Glob("taskranger/util/*.cpp")
sources += env.Glob("taskranger/data/*.cpp")
sources += env.Glob("taskranger/data/attributes/*.cpp")
sources += env.Glob("taskranger/config/*.cpp")

env.appendSourcePath("#src/")
env.appendSourcePath("#tabulate/include")

lib = env.Library("taskranger", sources)

exeEnv = env.Clone()
exeEnv.withLibraries(lib, append = False)

# The executable is named after the program instead of a shorthand function in order to avoid collisions with other todo programs.
# Shell aliases can be manually added if necessary.
taskranger = exeEnv.Program("taskranger", "taskranger/Main.cpp")

Default(taskranger)

# Hack to make sure the database is built
if (database is not None):
    Depends(taskranger, database)

Return("taskranger")
