# Defines a CI workflow
name: CI

# ... which is run when:
on:
  # ... something is pushed to one or more branches, or;
  push:
    branches: [ master ]
  # ... a PR is made to one or more branches.
  pull_request:
    branches: [ master ]



# When the trigger conditions are met, run the jobs
jobs:  
  # This job installs the base dependencies. 
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++-9, clang++-9]
    steps:
    - uses: actions/checkout@v2
      submodules: recursive
    # Set up python; requires for SCons and Conan
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install scons conan
    - name: Build
      run: |
        export CXX=${{ matrix.compiler }}
        conan profile new --detect $CXX
        profile=$CXX scons
        ./build/${CXX}.posix.64bit.dbg/src/bin/taskranger
        
